version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: boto3
    versions:
    - "> 1.13.11, < 1.14"
  - dependency-name: boto3
    versions:
    - ">= 1.14.a, < 1.15"
  - dependency-name: flake8
    versions:
    - "> 3.8.1, < 3.9"
  - dependency-name: pytest
    versions:
    - "> 5.4.2, < 5.5"
  - dependency-name: pytest-mock
    versions:
    - "> 3.1.0, < 3.2"
  - dependency-name: boto3
    versions:
    - 1.16.59
    - 1.16.63
    - 1.17.12
    - 1.17.17
    - 1.17.22
    - 1.17.27
    - 1.17.33
    - 1.17.39
    - 1.17.44
    - 1.17.49
    - 1.17.53
    - 1.17.57
